### PR TITLE
Add support for special suites supporting both EXtra-foam and Karabo

### PR DESCRIPTION
**Pull request by JamesWrigley**
Some special suites may want to support processing data from both EXtra-foam and
Karabo bridges, this is now possible by passing ClientType.BOTH to the
constructor of _SpecialAnalysisBase(). More generally, this replaces the
`client_klass` parameter of create_special() with an argument to the
_SpecialAnalysisBase() constructor.

If both client types are supported, then a combo box will be available for the
user to select the appropriate source.

### CODE REVIEW

**Review by CammilleCC — APPROVED** [review]
This is a cool addition! I would suggest putting the `client_support` as class variable, or would you foresee changes on the instantiation itself?

Aside from that, LGTM

**Comment by JamesWrigley** [comment]
No, I just want to make `create_special()` unnecessary :P IMHO it's overcomplicated and I want to get rid of it at some point, so that's why I made `client_support` a regular parameter. Is there an advantage to making it a class variable?

**Comment by CammilleCC** [comment]
I see, then I support you with that endeavor :P

It's more of flavor, TBH. I oought to use class variables as annotation (similar with title and long title). Using it also somewhat makes code cleaner because it reduces passed arguments and variable creation on init. But it's of course up to you :D

**Comment by JamesWrigley** [comment]
Actually that's a good point about `_[long_]title`. I was hesitant to make it a class variable because it means that inheriting classes would need to know about that field (that's the advantage of `create_special()`) but I forgot that the title fields already do this. Made `_client_support` a class field in 315008fb.

**Pull request merged**
